$App = "AAA"
$Stage1 = "DevQA"
$Stage2 = "Prod"
$Stage1code = "dqa"
$Stage2code = "prod"
$Site4 = "westus"
$Site4code = "wus"
$Site4Stage1CRRG = "rb-$Site4code-$App-$Stage1code-csrcr-rg01"
$Site4Stage2CRRG = "rb-$Site4code-$App-$Stage2code-csrcr-rg01"
$Site4Stage1VNETName = "rb-$Site4code-$App-$Stage1code-vn01"
$Site4Stage2VNETName = "rb-$Site4code-$App-$Stage2code-vn01"
$Site4Stage1AddressPrefix = "192.168.48.0/20"
$Site4Stage2AddressPrefix = "192.168.160.0/20"
$Site4Stage1MgmtSubnetName = "rb-$Site4code-$App-$Stage1code-vn01-sn01"
$Site4Stage1OutsideSubnetName = "rb-$Site4code-$App-$Stage1code-vn01-sn02"
$Site4Stage1DMZSubnetName = "rb-$Site4code-$App-$Stage1code-vn01-sn03"
$Site4Stage1InsideSubnetName = "rb-$Site4code-$App-$Stage1code-vn01-sn04"
$Site4Stage2MgmtSubnetName = "rb-$Site4code-$App-$Stage2code-vn01-sn01"
$Site4Stage2OutsideSubnetName = "rb-$Site4code-$App-$Stage2code-vn01-sn02"
$Site4Stage2DMZSubnetName = "rb-$Site4code-$App-$Stage2code-vn01-sn03"
$Site4Stage2InsideSubnetName = "rb-$Site4code-$App-$Stage2code-vn01-sn04"
$Site4Stage1MgmtSubnetPrefix = "192.168.48.0/24"
$Site4Stage1OutsideSubnetPrefix = "192.168.49.0/24"
$Site4Stage1DMZSubnetPrefix = "192.168.50.0/24"
$Site4Stage1InsideSubnetPrefix = "192.168.51.0/24"
$Site4Stage2MgmtSubnetPrefix = "192.168.160.0/24"
$Site4Stage2OutsideSubnetPrefix = "192.168.161.0/24"
$Site4Stage2DMZSubnetPrefix = "192.168.162.0/24"
$Site4Stage2InsideSubnetPrefix = "192.168.163.0/24"


$Site4Stage1MgmtSubnet = New-AzureRmVirtualNetworkSubnetConfig -Name "$Site4Stage1MgmtSubnetName" -AddressPrefix "$Site4Stage1MgmtSubnetPrefix"
$Site4Stage1OutsideSubnet = New-AzureRmVirtualNetworkSubnetConfig -Name "$Site4Stage1OutsideSubnetName" -AddressPrefix "$Site4Stage1OutsideSubnetPrefix"
$Site4Stage1DMZSubnet = New-AzureRmVirtualNetworkSubnetConfig -Name "$Site4Stage1DMZSubnetName" -AddressPrefix "$Site4Stage1DMZSubnetPrefix"
$Site4Stage1InsideSubnet = New-AzureRmVirtualNetworkSubnetConfig -Name "$Site4Stage1InsideSubnetName" -AddressPrefix "$Site4Stage1InsideSubnetPrefix"

$Site4Stage2MgmtSubnet = New-AzureRmVirtualNetworkSubnetConfig -Name "$Site4Stage2MgmtSubnetName" -AddressPrefix "$Site4Stage2MgmtSubnetPrefix"
$Site4Stage2OutsideSubnet = New-AzureRmVirtualNetworkSubnetConfig -Name "$Site4Stage2OutsideSubnetName" -AddressPrefix "$Site4Stage2OutsideSubnetPrefix"
$Site4Stage2DMZSubnet = New-AzureRmVirtualNetworkSubnetConfig -Name "$Site4Stage2DMZSubnetName" -AddressPrefix "$Site4Stage2DMZSubnetPrefix"
$Site4Stage2InsideSubnet = New-AzureRmVirtualNetworkSubnetConfig -Name "$Site4Stage2InsideSubnetName" -AddressPrefix "$Site4Stage2InsideSubnetPrefix"


New-AzureRmVirtualNetwork -Name $Site4Stage1VNETName -ResourceGroupName $Site4Stage1CRRG -Location $Site4 -AddressPrefix $Site4Stage1AddressPrefix -Subnet $Site4Stage1MgmtSubnet,$Site4Stage1OutsideSubnet,$Site4Stage1DMZSubnet,$Site4Stage1InsideSubnet -Tag @{ App="$App";  Stage="$Stage1" }
New-AzureRmVirtualNetwork -Name $Site4Stage2VNETName -ResourceGroupName $Site4Stage2CRRG -Location $Site4 -AddressPrefix $Site4Stage2AddressPrefix -Subnet $Site4Stage2MgmtSubnet,$Site4Stage2OutsideSubnet,$Site4Stage2DMZSubnet,$Site4Stage2InsideSubnet -Tag @{ App="$App";  Stage="$Stage2" } 