Remove-AzureRmResourceGroup -Name rb-we-aaa-dqa-csrvm-rg101 -force
Remove-AzureRmResourceGroup -Name rb-we-aaa-dqa-csrvm-rg102 -force
Remove-AzureRmResourceGroup -Name rb-ne-aaa-dqa-csrvm-rg101 -force
Remove-AzureRmResourceGroup -Name rb-ne-aaa-dqa-csrvm-rg102 -force
Remove-AzureRmResourceGroup -Name rb-eus-aaa-dqa-csrvm-rg101 -force
Remove-AzureRmResourceGroup -Name rb-eus-aaa-dqa-csrvm-rg102 -force
Remove-AzureRmResourceGroup -Name rb-we-aaa-prod-csrvm-rg101 -force
Remove-AzureRmResourceGroup -Name rb-we-aaa-prod-csrvm-rg102 -force
Remove-AzureRmResourceGroup -Name rb-ne-aaa-prod-csrvm-rg101 -force
Remove-AzureRmResourceGroup -Name rb-ne-aaa-prod-csrvm-rg102 -force
Remove-AzureRmResourceGroup -Name rb-eus-aaa-prod-csrvm-rg101 -force
Remove-AzureRmResourceGroup -Name rb-eus-aaa-prod-csrvm-rg102 -force

Remove-AzureRmResourceGroup -Name rb-we-aaa-dqa-csrvm-rg01 -force
Remove-AzureRmResourceGroup -Name rb-ne-aaa-dqa-csrvm-rg01 -force
Remove-AzureRmResourceGroup -Name rb-eus-aaa-dqa-csrvm-rg01 -force
Remove-AzureRmResourceGroup -Name rb-we-aaa-prod-csrvm-rg01 -force
Remove-AzureRmResourceGroup -Name rb-ne-aaa-prod-csrvm-rg01 -force
Remove-AzureRmResourceGroup -Name rb-eus-aaa-prod-csrvm-rg01 -force


Remove-AzureRmResourceGroup -Name rb-we-aaa-dqa-tstvm-rg01 -force
Remove-AzureRmResourceGroup -Name rb-ne-aaa-dqa-tstvm-rg01 -force
Remove-AzureRmResourceGroup -Name rb-eus-aaa-dqa-tstvm-rg01 -force
Remove-AzureRmResourceGroup -Name rb-we-aaa-prod-tstvm-rg01 -force
Remove-AzureRmResourceGroup -Name rb-ne-aaa-prod-tstvm-rg01 -force
Remove-AzureRmResourceGroup -Name rb-eus-aaa-prod-tstvm-rg01 -force
Remove-AzureRmResourceGroup -Name rb-we-aaa-dqa-csrcr-rg01 -force
Remove-AzureRmResourceGroup -Name rb-ne-aaa-dqa-csrcr-rg01 -force
Remove-AzureRmResourceGroup -Name rb-eus-aaa-dqa-csrcr-rg01 -force
Remove-AzureRmResourceGroup -Name rb-we-aaa-prod-csrcr-rg01 -force
Remove-AzureRmResourceGroup -Name rb-ne-aaa-prod-csrcr-rg01 -force
Remove-AzureRmResourceGroup -Name rb-eus-aaa-prod-csrcr-rg01 -force
Remove-AzureRmResourceGroup -Name rb-we-aaa-dqa-sdisk-rg01 -force
Remove-AzureRmResourceGroup -Name rb-ne-aaa-dqa-sdisk-rg01 -force
Remove-AzureRmResourceGroup -Name rb-eus-aaa-dqa-sdisk-rg01 -force
Remove-AzureRmResourceGroup -Name rb-we-aaa-prod-sdisk-rg01 -force
Remove-AzureRmResourceGroup -Name rb-ne-aaa-prod-sdisk-rg01 -force
Remove-AzureRmResourceGroup -Name rb-eus-aaa-prod-sdisk-rg01 -force
Remove-AzureRmResourceGroup -Name rb-we-aaa-dqa-sdiag-rg01 -force
Remove-AzureRmResourceGroup -Name rb-ne-aaa-dqa-sdiag-rg01 -force
Remove-AzureRmResourceGroup -Name rb-eus-aaa-dqa-sdiag-rg01 -force
Remove-AzureRmResourceGroup -Name rb-we-aaa-prod-sdiag-rg01 -force
Remove-AzureRmResourceGroup -Name rb-ne-aaa-prod-sdiag-rg01 -force
Remove-AzureRmResourceGroup -Name rb-eus-aaa-prod-sdiag-rg01 -force
Remove-AzureRmResourceGroup -Name rb-we-aaa-dqa-pipm-rg01 -force
Remove-AzureRmResourceGroup -Name rb-ne-aaa-dqa-pipm-rg01 -force
Remove-AzureRmResourceGroup -Name rb-eus-aaa-dqa-pipm-rg01 -force
Remove-AzureRmResourceGroup -Name rb-we-aaa-prod-pipm-rg01 -force
Remove-AzureRmResourceGroup -Name rb-ne-aaa-prod-pipm-rg01 -force
Remove-AzureRmResourceGroup -Name rb-eus-aaa-prod-pipm-rg01 -force
Remove-AzureRmResourceGroup -Name rb-we-aaa-dqa-pipd-rg01 -force
Remove-AzureRmResourceGroup -Name rb-ne-aaa-dqa-pipd-rg01 -force
Remove-AzureRmResourceGroup -Name rb-eus-aaa-dqa-pipd-rg01 -force
Remove-AzureRmResourceGroup -Name rb-we-aaa-prod-pipd-rg01 -force
Remove-AzureRmResourceGroup -Name rb-ne-aaa-prod-pipd-rg01 -force
Remove-AzureRmResourceGroup -Name rb-eus-aaa-prod-pipd-rg01 -force
